version: '3'
services:
  subspace:
    image: ssiu/subspace:latest
    build:
      context: ./build/subspace
    container_name: subspace
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - SUBSPACE_HTTP_HOST=${SUBSPACE_HTTP_HOST:-subspace.example.com}
      - SUBSPACE_HTTP_ADDR=${SUBSPACE_HTTP_ADDR:-:80}
      - SUBSPACE_LETSENCRYPT=${SUBSPACE_LETSENCRYPT:-true}
      - SUBSPACE_HTTP_INSECURE=${SUBSPACE_HTTP_INSECURE:-false}
      - SUBSPACE_ENDPOINT_IP_AUTO_DETECT=${SUBSPACE_ENDPOINT_IP_AUTO_DETECT:-false}
      - SUBSPACE_DNSMASQ_DISABLED=${SUBSPACE_DNSMASQ_DISABLED:-0}
      - SUBSPACE_LISTENPORT=${SUBSPACE_LISTENPORT:-51820}
      - SUBSPACE_IPV4_POOL=${SUBSPACE_IPV4_NETWORK:-10.99.97}.0/24
      - SUBSPACE_IPV6_POOL=${SUBSPACE_IPV6_NETWORKL-fd00::10:97}:0/64
      - SUBSPACE_NAMESERVER=1.1.1.1
      - SUBSPACE_IPV6_NAT_ENABLED=${SUBSPACE_IPV6_NAT_ENABLED:-1}
    volumes:
      - ./data/subspace:/data:Z
    network_mode: host
    cap_add:
      - NET_ADMIN
  dnscrypt-proxy:
    image: ssiu/dnscrypt-proxy:latest
    container_name: dnscrypt-proxy
    depends_on:
      - subspace
    build:
      context: ./build/dnscrypt-proxy
      args:
        - DNSCRYPT_PORT=${DNSCRYPT_PORT:-53}
    restart: always
    ports:
      - ${SUBSPACE_IPV4_NETWORK:-10.99.97}.1:${DNSCRYPT_PORT:-53}:5053/udp
      - ${SUBSPACE_IPV4_NETWORK:-10.99.97}.1:${DNSCRYPT_PORT:-53}:5053/tcp
  torproxy:
    image: ssiu/torproxy:latest
    container_name: torproxy
    depends_on:
      - subspace
    build:
      context: ./build/torproxy
      args:
        - DNS_PORT=${TOR_DNS_PORT:-5353}
    restart: always
    ports:
      - ${SUBSPACE_IPV4_NETWORK:-10.99.97}.1:9050:9050
    environment:
      - LOCATION=${TOR_LOCATION:-UK}
